name: running-tests
on:
  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Pause for 25 seconds
        run: |
          echo "this is only a test"
          sleep 25
