name: Master
on:
  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Pause for 25 seconds
        run: |
          echo $INPUT_FOO
          echo "this is only a test"
          sleep 25
