name: Trigger E2E Tests

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger e2e tests
        uses: tmart134/trigger-workflow-and-wait@master
        with:
          owner: tmart134
          repo: example-repo
          github_token: $({ secrets.TOKEN })
          workflow_file_name: main.yml
          ref: update-readme
          wait_interval: 5
          propagate_failure: false
          trigger_workflow: true
          wait_workflow: true
