name: Run script to update Tests by Tags doc

on:
  push:
    branches:
      - main
    paths:
      - 'tests/**'
  
jobs:
  run-on-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run script to update Tests by Tags doc
        run: |
          echo "The /tests directory has been changed. Let's update the Tests by Tags doc" $(date)
          > my_file.md
      
      - name: Check for changes
        id: check_changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "changes=true" >> "$GITHUB_OUTPUT"
          else
            echo "changes=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Commit changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git add .
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -m "generated new tests by tags doc"
          git push