name: Run script to update Tests by Tags doc

on:
  push:
    branches:
      - main
    paths:
      - 'tests/**'
  
jobs:
  run-on-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run script to update Tests by Tags doc
        run: |
          echo "The /tests directory has been changed. Let's update the Tests by Tags doc" $(date)
          > my_file.md
      
      - name: Check for changes
        run: |
          if git diff --exit-code; then
            echo "::set-env name=doc_updated::false"
          else
            echo "::set-env name=doc_updated::true"
          fi

      - name: Commit changes
        if env.doc_updated == 'true'
        run: |
          git add .
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -m "generated new tests by tags doc"
          git push