name: Run script to update Tests by Tags doc

on:
  push:
    branches:
      - main
    paths:
      - 'tests/**'
  
jobs:
  run-on-merge:
    runs-on: ubuntu-latest

    permissions: 
       contents: write
       pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run script to update Tests by Tags doc
        run: |
          echo "The /tests directory has been changed. Let's update the Tests by Tags doc $(date)"
          cat docs/my_file.md
          echo "$(git status)"
      
      - name: Check for changes
        id: check_changes
        run: |
          if [[ -n "$(git status --porcelain docs/)" ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "there are no file changes"
          fi

      - name: Commit and push
        id: commit_and_push
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b update-docs-${{ github.sha }}
          git add .
          git commit -m "Automated update to Tests by tags doc"
          git push origin update-docs-${{ github.sha }}
    
      - name: Create a PR
        if: steps.commit_and_push.result == 'success'
        run: |
          gh pr create -B main -H update-docs-${{ github.sha }} --title "Automated Update to docs" --body "This is an update to the Test by tags doc"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}